ARG NODE_VERSION=16.17.1

FROM node:${NODE_VERSION}-alpine

WORKDIR /

ARG PORT=3000

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_ENV=production

ENV PORT=$PORT

COPY . ./socket-server
# Optional, only needed if you rely on unbundled dependencies
# COPY --from=build /src/node_modules /src/node_modules

CMD [ "node", "./socket-server/server.ts" ]