ARG NODE_VERSION=18.19.0

FROM node:${NODE_VERSION}-alpine

WORKDIR /app/

ARG PORT=3000

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_ENV=production
ENV REDIS_BASE /opt/redis

ENV PORT=$PORT

COPY . .

# COPY package*.json .

RUN npm install


RUN apk --update add redis supervisor


EXPOSE 3000
CMD ["/usr/bin/supervisord", "-c", "/app/docker/supervisord.conf"]