ARG NODE_VERSION=18.19.0

FROM node:${NODE_VERSION}-alpine

WORKDIR /app/

ARG PORT=3000

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_ENV=production
# ENV REDIS_BASE /opt/redis

ENV PORT=$PORT

COPY package*.json .
RUN npm install

COPY . .

# RUN apk --update add redis

# Install supervisor
# RUN mkdir -p /var/log/supervisor
# RUN easy_install supervisor

# COPY ./ ./websocket
# Optional, only needed if you rely on unbundled dependencies
# COPY --from=build /src/node_modules /src/node_modules


EXPOSE 3000
CMD ["npm", "start"]