name: Redeploy jelastic and notify

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  redeploy-and-notify:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Show env var
        run: |
          echo "${{ vars.CHAT_KEY }} ${{ vars.ENV_NAME }} ${{ vars.TAG }} ${{ vars.NODE_ID }}"
      - name: Redeploy Container
        uses: Marvelous-Digital/github-actions-jelastic@master
        with:
          jelastic_url: app.jpc.infomaniak.com
          jelastic_username: ${{ secrets.JELASTIC_USERNAME }}
          jelastic_password: ${{ secrets.JELASTIC_TOKEN }}
          task: environment/control/redeploycontainers --nodeId ${{ vars.NODE_ID }} --envName ${{ vars.ENV_NAME }} --tag ${{ vars.TAG }}
      # - name: Google Chat Notification
      #   uses: Co-qn/google-chat-notification@releases/v1
      #   with:
      #     name: Deploy
      #     url: '${{ vars.CHAT_KEY }}'
      #     status: ${{ job.status }}
      #   if: always()
